name: "Bug report"
description: Report an issue
title: '[bug]: '
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for taking the time to create a bug report. Please search open/closed issues before submitting, as the issue may have already been reported/addressed.
 
  - type: markdown
    attributes:
      value: |
        #### If you aren't sure this is a bug or not, please open a discussion instead:
        - [Discussions](https://github.com/smakosh/roll-your-own-auth/discussions/new?category=general)

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us how in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true

  - type: input
    id: part-affected
    attributes:
      label: Affected part/parts
      description: Is this feature request relevant to any of the already existing examples?
      placeholder: ex. rest-express-prisma-jwt-sqlite, rest-express-prisma-session-sqlite...
    validations:
      required: false

  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce
      description:  A step-by-step description of how to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true

  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Information about browsers, system or binaries that's relevant.
      render: bash
      placeholder: System, Binaries, Browsers
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Before submitting
      description: By submitting this issue, you agree to follow our [Contributing Guidelines](https://github.com/smakosh/roll-your-own-auth/blob/main/CONTRIBUTING.md).
      options:
        - label: I've made research efforts and searched the documentation
          required: true
        - label: I've searched for existing issues
          required: true